export const keywordList=[
{district: "GANGNAM", value: "다채로운 문화도시, 강남"},
{distirict: "SONGPA", value: "파동이 닿는 곳, 송파"},
{district: "GANGBOOK", value: "초록의 도시, 강북"},
{distirict: "GANGSEO", value:"설렘의 소리로 가득한 강서"},
{district: "GWANACK", value: "청춘이 시작되는 곳, 관악"},
{distirict: "GWANGJIN", value:"아이들의 미소를 품은 곳, 광진"},
{district: "GOORO", value: "애환과 열정이 공존하는 곳, 구로"},
{distirict: "GUEMCHON", value: "동네방네, 행복도시 금천"},
{district: "NOWON", value: "세월의 흐름을 간직한 곳, 노원"},
{distirict: "DOBONG", value: "추억이 묻은 고향, 도봉"},
{district: "DONGDAEMOON", value: "만남의 도시, 동대문"},
{distirict: "DONGJAK", value: "사유하는 동네, 동작"},
{district: "MAPO", value: "새로운 인연이 시작하는 곳, 마포"},
{distirict: "SEODAEMOON", value: "활력을 얻다, 서대문"},
{district: "SEOCHO", value: "다채로운 예술도시, 서초"},
{distirict: "SEONGDONG", value: "함께하는 치유도시, 성동"},
{district: "SEONGBOOK", value: "서울토박이, 성북"},
{distirict: "GANGDONG", value:"역사가 깃든 곳, 강동"},
{district: "YANGCHON", value: "낯설지만 친근한, 양천"},
{distirict: "YEONGDEUNGPO", value: "한강 위 노을이 물든 도시, 영등포"},
{district: "YONGSAN", value: "헌 것부터 새 것까지, 모든 이야기를 담은 용산"},
{distirict: "EUNPYEONG", value: "평화가 깃든 곳, 은평"},
{distirict: "JONGRO", value: "현대와 과거의 만남, 종로"},
{district: "JOONGO", value: "서울의 터줏대감, 중구"},
{distirict: "JOONGRANG", value: "오래 머무를스록 아름다운 중랑"}]